/**
 * Copies the browser builds of the renderer's third-party modules into
 * `src/web/js` (generated at `postinstall`, not committed). The engine and
 * the connectors are served as plain static files over `hakuneko://cache`,
 * so they cannot resolve `node_modules`:
 * - `fflate.mjs`      ES module, reachable as the bare specifier `fflate`
 *                     through the import map in `src/web/index.html`.
 * - `protobuf.min.js` UMD bundle, loaded on first use by `engine/Protobuf.mjs`.
 * The versions follow the root `devDependencies`, so the deprecated-gate and
 * dependency updates cover them.
 */
const fs = require('node:fs');
const path = require('node:path');

const TARGET = path.resolve(__dirname, '..', 'src', 'web', 'js');

// `exports` maps hide the files from `require.resolve(<pkg>/<file>)`: locate the package root from its entry point instead
function packageRoot(name, entry) {
    let directory = path.dirname(entry);
    while (!fs.existsSync(path.join(directory, 'package.json')) || JSON.parse(fs.readFileSync(path.join(directory, 'package.json'), 'utf8')).name !== name) {
        const parent = path.dirname(directory);
        if (parent === directory) {
            throw new Error(`Cannot locate the package root of "${name}"!`);
        }
        directory = parent;
    }
    return directory;
}

const FILES = [
    { name: 'fflate', entry: require.resolve('fflate'), source: path.join('esm', 'browser.js'), target: 'fflate.mjs', license: 'MIT', module: true },
    { name: 'protobufjs', entry: require.resolve('protobufjs'), source: path.join('dist', 'protobuf.min.js'), target: 'protobuf.min.js', license: 'BSD-3-Clause', module: false }
];

fs.mkdirSync(TARGET, { recursive: true });
for (const file of FILES) {
    const root = packageRoot(file.name, file.entry);
    const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    const source = fs.readFileSync(path.join(root, file.source), 'utf8');
    if (file.module && /^\s*import\s/m.test(source)) {
        throw new Error(`${file.name}/${file.source} imports other modules and cannot be vendored as a single file!`);
    }
    const header = `/*! ${file.name} v${version} (${file.license}) - generated by scripts/vendor.js, do not edit */\n`;
    fs.writeFileSync(path.join(TARGET, file.target), header + source);
    console.log(`vendored ${file.name}@${version} -> src/web/js/${file.target}`);
}
